//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hola.modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int Id_venta { get; set; }
        public int Fecha { get; set; }
        public int Precio { get; set; }
        public int Id_libro { get; set; }
        public int Id_cliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Libro Libro { get; set; }
    }
}
